//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookTable
    {
        public int bookId { get; set; }
        public string bookTitle { get; set; }
        public string bookDesc { get; set; }
        public string bookAuthor { get; set; }
        public int bookCount { get; set; }
    }
}
